language: python
python:
    - "3.6"

services:
    - docker

# Command to install dependencies
#install:
#    pip install -r flask/requirements.txt



jobs:
    include:
#        - stage: linting
#          install:
#            - pip install flake8
#          script:
#            - flake8 flask
        - stage: docker
          script:
            - docker login -u _json_key -p "$(echo $REGISTRY_KEY)" https://eu.gcr.io
            - docker build -t eu.gcr.io/xomnia-search-engine-training/flask:latest ./flask
            - docker push eu.gcr.io/xomnia-search-engine-training/flask:latest
            - docker build -t eu.gcr.io/xomnia-search-engine-training/scraper:latest ./scraper
            - docker push eu.gcr.io/xomnia-search-engine-training/scraper:latest
        - stage: k8s
          script:
            - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
            - source /home/travis/google-cloud-sdk/path.bash.inc
            - gcloud version
            - gcloud components update kubectl || true
            - echo $REGISTRY_KEY > lekeyfile.json
            - gcloud auth activate-service-account $GCLOUD_EMAIL --key-file lekeyfile.json
            - gcloud container clusters get-credentials make-it-binger-cluster-clone-1 --zone europe-west1-c --project xomnia-search-engine-training
            - cd deployment
            - ./deploy.sh
            - kubectl delete pods -l app=flask
            - kubectl delete pods -l app=scraper
