language: python
python:
    - "3.6"

services:
    - docker

# Command to install dependencies
#install:
#    pip install -r flask/requirements.txt



jobs:
    include:
#        - stage: linting
#          install:
#            - pip install flake8
#          script:
#            - flake8 flask
        - stage: docker
          script:
            - docker login -u _json_key -p "$(echo $REGISTRY_KEY)" https://eu.gcr.io
            - docker build -t eu.gcr.io/xomnia-search-engine-training/flask:latest ./flask
            - docker push eu.gcr.io/xomnia-search-engine-training/flask:latest
        - stage: k8s
          script:
            - curl https://sdk.cloud.google.com | bash;
            - gcloud version
#            - install gcloud
#            - authenticate gcloud
#            - update gcloud kubectl component
#            - configure kubectl
#            - kubectl apply -f deployment/flask.yaml
#            - kubectl delete pods -l app=flask